"""FilmFoundry v3 production contracts.

The package is intentionally dependency free.  It validates machine contracts
without making claims about provider obedience or visual quality.
"""
from .contracts import (
    LIFECYCLE_STATES,
    parse_prompt_metadata,
    resolve_manifest_path,
    validate_asset_registry,
    validate_evidence,
    validate_prompt_markdown,
    validate_production_state,
    validate_reference_graph,
    validate_shot_spec,
    validate_state_transition,
    validate_workspace_manifest,
)
from .report import ValidationIssue, ValidationReport
from .adapters import CompiledPayload, ProviderAdapter
from .validation import validate_workspace
from .compiler import compile_canonical, compile_prompt
from .handoff import (
    HANDOFF_SECTIONS,
    HANDOFF_STATUSES,
    ProviderNeutralHandoff,
    build_provider_neutral_handoff,
    validate_provider_neutral_handoff,
)
from .profiles import (
    ProjectProfile,
    StyleProfile,
    load_profile,
    validate_project_profile,
    validate_style_profile,
)
from .decision import (
    CreatorDecisionBrief,
    CreatorDecisionOption,
    DecisionStatus,
    build_creator_decision_brief,
)
from .visual_control import VisualControlPlan, parse_visual_control, validate_visual_control
from .alignment import validate_visual_control_alignment
from .experiments import record_experiment_result
from .capabilities import CapabilitySnapshot, capability_allows, load_capability_snapshot
from .ledger import (
    ArtifactRequirement,
    RequirementReport,
    evaluate_requirements,
    production_ledger_report,
    validate_production_ledger,
    validate_production_policy,
)
from .script_analysis import ScriptAnalysis, parse_script_analysis, validate_script_analysis
from .beat_map import EmotionalBeatMap, parse_emotional_beat_map, production_requirement_facts, validate_emotional_beat_map
from .scene_topology import SceneTopology, parse_scene_topology, validate_scene_topology
from .coverage import LocationCoverageSet, parse_location_coverage, validate_location_coverage
from .look_bible import LookBible, parse_look_bible, validate_look_bible
from .dependency_graph import DependencyGraph, build_dependency_graph, parse_dependency_graph, validate_dependency_graph
from .creator_sources import (
    CreatorCatalogSource,
    CreatorProjectAdapter,
    CreatorSourceCatalog,
    CreatorSourceCoverageGap,
    discover_creator_sources,
)
from .creator_read_model import (
    CreatorAction,
    CreatorAsset,
    CreatorBlocker,
    CreatorConflict,
    CreatorContinuityEdge,
    CreatorCoverage,
    CreatorEmotionPoint,
    CreatorMetric,
    CreatorNarrativeNode,
    CreatorNavigation,
    CreatorOverview,
    CreatorProvenance,
    CreatorReadModel,
    CreatorShot,
    CreatorSnapshot,
    CreatorSourceRef,
    CreatorTerminologyRegistry,
    TERMINOLOGY_REGISTRY,
    TERMINOLOGY_SCHEMA_VERSION,
    build_creator_read_model,
    collect_creator_snapshot,
    derive_creator_navigation,
    get_creator_terminology,
    terminology_label,
    translate_creator_term,
)
from .modes import (
    LANE_FAST,
    LANE_RECOVERY,
    LANE_STANDARD,
    LANE_STRICT,
    MODE_COMMIT,
    MODE_CREATIVE,
    MODE_GATE,
    MODE_PRODUCTION,
    ModeDecision,
    ExecutionBudget,
    ExecutionLane,
    RiskLevel,
    CreationGoal,
    CreationGoalDecision,
    GOAL_EXISTING_SCRIPT,
    GOAL_FROM_ZERO_IDEA,
    GOAL_GENERAL_CREATIVE,
    GOAL_SCENE_ASSET,
    GOAL_SHORT_VIDEO_TEST,
    GOAL_SINGLE_SHOT_PROMPT,
    GOAL_STYLE_EXPLORATION,
    mode_output_contract,
    reference_profile,
    route_creation_goal,
    route_request,
    execution_budget,
)
from .render import FORMAT_NAMES, VIEW_NAMES, render_read_model

__version__ = "3.0.0"

__all__ = [
    "LIFECYCLE_STATES",
    "parse_prompt_metadata",
    "resolve_manifest_path",
    "validate_asset_registry",
    "validate_evidence",
    "validate_prompt_markdown",
    "validate_production_state",
    "validate_reference_graph",
    "validate_shot_spec",
    "validate_state_transition",
    "validate_workspace_manifest",
    "__version__",
    "ValidationIssue",
    "ValidationReport",
    "CompiledPayload",
    "ProviderAdapter",
    "validate_workspace",
    "compile_canonical",
    "compile_prompt",
    "HANDOFF_SECTIONS",
    "HANDOFF_STATUSES",
    "ProviderNeutralHandoff",
    "build_provider_neutral_handoff",
    "validate_provider_neutral_handoff",
    "ProjectProfile",
    "StyleProfile",
    "load_profile",
    "validate_project_profile",
    "validate_style_profile",
    "CreatorDecisionBrief",
    "CreatorDecisionOption",
    "DecisionStatus",
    "build_creator_decision_brief",
    "VisualControlPlan",
    "parse_visual_control",
    "validate_visual_control",
    "validate_visual_control_alignment",
    "record_experiment_result",
    "CapabilitySnapshot",
    "capability_allows",
    "load_capability_snapshot",
    "ArtifactRequirement",
    "RequirementReport",
    "evaluate_requirements",
    "production_ledger_report",
    "validate_production_ledger",
    "validate_production_policy",
    "ScriptAnalysis",
    "parse_script_analysis",
    "validate_script_analysis",
    "EmotionalBeatMap",
    "parse_emotional_beat_map",
    "validate_emotional_beat_map",
    "production_requirement_facts",
    "SceneTopology",
    "parse_scene_topology",
    "validate_scene_topology",
    "LocationCoverageSet",
    "parse_location_coverage",
    "validate_location_coverage",
    "LookBible",
    "parse_look_bible",
    "validate_look_bible",
    "DependencyGraph",
    "build_dependency_graph",
    "parse_dependency_graph",
    "validate_dependency_graph",
    "CreatorCatalogSource",
    "CreatorProjectAdapter",
    "CreatorSourceCatalog",
    "CreatorSourceCoverageGap",
    "discover_creator_sources",
    "CreatorAction",
    "CreatorAsset",
    "CreatorBlocker",
    "CreatorConflict",
    "CreatorContinuityEdge",
    "CreatorCoverage",
    "CreatorEmotionPoint",
    "CreatorMetric",
    "CreatorNarrativeNode",
    "CreatorNavigation",
    "CreatorOverview",
    "CreatorProvenance",
    "CreatorReadModel",
    "CreatorShot",
    "CreatorSnapshot",
    "CreatorSourceRef",
    "CreatorTerminologyRegistry",
    "TERMINOLOGY_REGISTRY",
    "TERMINOLOGY_SCHEMA_VERSION",
    "build_creator_read_model",
    "collect_creator_snapshot",
    "derive_creator_navigation",
    "get_creator_terminology",
    "terminology_label",
    "translate_creator_term",
    "MODE_COMMIT",
    "MODE_CREATIVE",
    "MODE_GATE",
    "MODE_PRODUCTION",
    "LANE_FAST",
    "LANE_STANDARD",
    "LANE_STRICT",
    "LANE_RECOVERY",
    "ModeDecision",
    "ExecutionBudget",
    "ExecutionLane",
    "RiskLevel",
    "CreationGoal",
    "CreationGoalDecision",
    "GOAL_EXISTING_SCRIPT",
    "GOAL_FROM_ZERO_IDEA",
    "GOAL_GENERAL_CREATIVE",
    "GOAL_SCENE_ASSET",
    "GOAL_SHORT_VIDEO_TEST",
    "GOAL_SINGLE_SHOT_PROMPT",
    "GOAL_STYLE_EXPLORATION",
    "mode_output_contract",
    "reference_profile",
    "route_creation_goal",
    "route_request",
    "execution_budget",
    "FORMAT_NAMES",
    "VIEW_NAMES",
    "render_read_model",
]
